image_size = 64
channesl: 1

# Flow matching
epochs: 20
batch_size = 256
lr : 0.005
cin : 32
cfg_drop_p: 0.1
cfg_scale : 3.0
ode_steps : 50

# classifier
clf_batch : 512
clf_lr : 0.0005
clf_epochs : 50
early_stop_patience: 3